general.import = [
  "~/.config/alacritty/themes/nord.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
normal.family = "RecMonoLinear Nerd Font"

size = 15


